services:
  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    ports:
      - 8080:8080
    networks:
      - keycloak
    depends_on:
      - postgres-keycloak
  postgres-keycloak:
    container_name: pg-keycloak
    image: postgres
    environment:
      - POSTGRES_DB=keyclaock_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - 7070:5432
    networks:
      - keycloak
networks:
  keycloak: { }
